FusionIIIT/Fusion/urls.py
import notifications.urls
import debug_toolbar
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls')),
    url(r'^aims/', include('applications.academic_information.urls')),
    url(r'^notifications/', include('applications.notifications_extension.urls')),
    url(r'^estate/', include('applications.estate_module.urls')),
    url(r'^dep/', include('applications.department.urls')),
    url(r'^programme_curriculum/',include('applications.programme_curriculum.urls')),
    url(r'^iwdModuleV2/', include('applications.iwdModuleV2.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^research_procedures/', include('applications.research_procedures.urls')),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^eis/', include('applications.eis.urls')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^purchase-and-store/', include('applications.ps1.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^establishment/', include('applications.establishment.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^counselling/', include('applications.counselling_cell.urls')),
    url(r'^hostelmanagement/', include('applications.hostel_management.urls')),
    url(r'^income-expenditure/', include('applications.income_expenditure.urls')),
    url(r'^hr2/', include('applications.hr2.urls')),
    url(r'^recruitment/', include('applications.recruitment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FusionIIIT/applications/hostel_management/urls.py
from django.urls import path
from . import views

app_name = 'hostelmanagement'

urlpatterns = [
    #Home 
    path('', views.hostel_view, name="hostel_view"),

    #Notice Board
    path('notice_form/', views.notice_board, name="notice_board"),
    path('delete_notice/', views.delete_notice, name="delete_notice"),

    #Worker Schedule
    path('edit_schedule/', views.staff_edit_schedule, name='staff_edit_schedule'),
    path('delete_schedule/', views.staff_delete_schedule, name='staff_delete_schedule'),
    
    #Student Room
    path('edit_student/',views.edit_student_room,name="edit_student_room"),
    path('edit_student_rooms_sheet/', views.edit_student_rooms_sheet, name="edit_student_rooms_sheet"),

    #Attendance
    path('edit_attendance/', views.edit_attendance, name='edit_attendance'),

    #Attendance
    path('edit_attendance/', views.edit_attendance, name='edit_attendance'),

    #Worker Report
    path('worker_report/', views.generate_worker_report, name='workerreport'),
    path('pdf/', views.GeneratePDF.as_view(), name="pdf"),
]

FusionIIIT/applications/office_module/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'office_module'

urlpatterns = [

    url(r'^officeOfDeanPnD/submit$',views.submitRequest,name='pWorkRequest'),
    url(r'^officeOfDeanPnD/action$',views.action,name='action'),
    url(r'^officeOfPurchaseOfficer/',views.officeOfPurchaseOfficer, name ='officeOfPurchaseOfficer'),
    url(r'^apply_purchase/', views.apply_purchase, name='apply_purchase'),
    url(r'^after_purchase/', views.after_purchase, name='after_purchase'),
    url(r'^officeOfRegistrar/$', views.officeOfRegistrar, name='officeOfRegistrar'),
    url(r'^officeOfRegistrar/response/ajax$', views.officeOfRegistrar_ajax_submit, name='officeOfRegistrar_ajax_submit'),
    #url(r'^officeOfRegistrar/assistantRegistrar/$', views.assistantRegistrar, name="assistantRegistrar"),
    url(r'^officeOfRegistrar/forward/(?P<id>[0-9]+)', views.officeOfRegistrar_forward, name='officeOfRegistrar_forward'),
    url(r'^officeOfRegistrar/forwardsubmit/$', views.officeOfRegistrar_forward_submit, name='officeOfRegistrar_forward_submit'),
    url(r'^officeOfDeanRSPC/$', views.officeOfDeanRSPC, name='officeOfDeanRSPC'),
    url(r'^newordershod/',views.newordershod,name='newordershod'),
    url(r'^newordershod2/',views.newordershod,name='newordershod2'),
    url(r'^newordersdirector/',views.newordersdirector,name='newordersdirector'),
    url(r'^add_items/',views.add_items,name='add_items'),
    url(r'^view_items/',views.view_items,name='view_items'),
    url(r'^newordersdirectorview/',views.newordersdirectorview,name='newordersdirectorview'),

    url(r'^newordersPOonGem/',views.newordersPOonGem,name='newordersPOonGem'),
    url(r'^newordersPO/',views.newordersPO,name='newordersPO'),
    url(r'^newordersregistrar/',views.newordersregistrar,name='newordersregistrar'),
    url(r'^newordersregistrar2/',views.newordersregistrar2,name='newordersregistrar2'),
    url(r'^officeOfDeanRSPC/submit/$',views.project_register,name='p_register'),
    url(r'^officeOfDeanRSPC/extention/$',views.project_extension,name='p_extension'),
    url(r'^officeOfDeanRSPC/close/$',views.project_closure,name='p_closure'),
    url(r'^officeOfDeanRSPC/reallocate/$',views.project_reallocation,name='p_reallocation'),
    url(r'^officeOfDeanRSPC/action/$',views.project_registration_permission,name='registration'),
    url(r'^officeOfDeanRSPC/extension/$',views.project_extension_permission,name='extension'),
    url(r'^officeOfDeanRSPC/closure/$',views.project_closure_permission,name='closure'),
    url(r'^officeOfDeanRSPC/reallocation/$',views.project_reallocation_permission,name='reallocation'),
    url(r'^officeOfDeanRSPC/forwarded/$',views.hod_action,name='hod_action'),
    url(r'^officeOfDeanRSPC/forwarded1/$',views.hod_closure,name='hod_closure'),
    url(r'^officeOfDeanRSPC/forwarded2/$',views.hod_extension,name='hod_extension'),
    url(r'^officeOfDeanRSPC/forwarded3/$',views.hod_allocation,name='hod_allocation'),
    url(r'^officeOfDeanRSPC/(?P<pr_id>[0-9]+)/$',views.pdf,name='pdf'),
    url(r'^officeOfDeanRSPC/registration_details/(?P<pr_id>[0-9]+)/$', views.reg_details, name='reg_details'),
    url(r'^officeOfDeanRSPC/extension_details/(?P<pr_id>[0-9]+)/$', views.ext_details, name='ext_details'),
    url(r'^officeOfDeanRSPC/closure_details/(?P<pr_id>[0-9]+)/$', views.closure_details, name='closure_details'),
    url(r'^officeOfDeanRSPC/reallocation_details/(?P<pr_id>[0-9]+)/$', views.reallocate_details,
        name='reallocate_details'),

    url(r'^eisModulenew/profile', views.eisModulenew, name='eisModulenew'),

    url(r'^officeOfDeanPnD/$', views.officeOfDeanPnD, name='officeOfDeanPnD'),
    url(r'^officeOfHOD/$', views.officeOfHOD, name='officeOfHOD'),
    url(r'^officeOfHOD/submit/$',views.teaching_form,name='teaching_form'),
    url(r'^officeOfHOD/work/$',views.hod_work,name='hod_work'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),



    url(r'^deleteitem/',views.delete_item, name='delete_item'),
    url(r'^deletevendor/(?P<id>[0-9]+)',views.delete_vendor, name='delete_vendor'),
    url(r'^editvendor/(?P<id>[0-9]+)',views.edit_vendor, name='edit_vendor'),
    url(r'^editvendor/office/officeOfPurchaseOfficer/edit/',views.edit,name='edit'),
    url(r'^edititem/(?P<id>[0-9]+)',views.edit_item, name='edit_item'),
    url(r'^edititem/office/officeOfPurchaseOfficer/edit1/',views.edit1,name='edit'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^directorOffice/$', views.directorOffice, name='directorOffice'),
    url(r'^directorOffice/viewProfile', views.viewProfile, name='viewProfile'),
    url(r'^directorOffice/viewFacProfile', views.viewFacProfile, name='viewFacProfile'),
    url(r'^directorOffice/viewStaffProfile', views.viewStaffProfile, name='viewStaffProfile'),
    url(r'^directorOffice/viewStudentProfile', views.viewStudentProfile, name='viewStudentProfile'),
    url(r'^directorOffice/viewOngoingProjects', views.viewOngoingProjects, name='viewOngoingProjects'),
    url(r'^directorOffice/viewOfficeBearers', views.viewOfficeBearers, name='viewOfficeBearers'),
    url(r'^directorOffice/meeting_dropdown', views.meeting_dropdown, name='meeting_dropdown'),
    url(r'^directorOffice/viewMeetings', views.viewMeetings, name='viewMeetings'),
    url(r'^directorOffice/viewHOD', views.viewHOD, name='viewHOD'),
    url(r'^directorOffice/meeting', views.meeting, name='meeting'),
    url(r'^directorOffice/planMeetings', views.planMeetings, name='planMeetings'),
    url(r'^officeOfRegistrar/view/(?P<id>[0-9]+)', views.officeOfRegistrar_view_file, name='registrar_view_file'),
    url(r'^officeOfRegistrar/upload/$', views.upload, name='upload'),
    url(r'^officeOfRegistrar/generalAdminForm/reject/$', csrf_exempt(views.admin_reject), name='admin_reject'),
    url(r'^officeOfDeanStudents/$', views.officeOfDeanStudents, name='officeOfDeanStudents'),
    url(r'^officeOfPurchaseOfficer/', views.officeOfPurchaseOfficr, name='officeOfPurchaseOfficer'),
    url(r'^officeOfRegistrar/', views.officeOfRegistrar, name='officeOfRegistrar'),

    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^officeOfDeanStudents/holding_meeting', views.holdingMeeting, name='holdingMeetings'),
    url(r'^officeOfDeanStudents/meeting_Minutes', views.meetingMinutes, name='meetingMinutes'),
    url(r'^officeOfDeanStudents/hostelRoomAllotment', views.hostelRoomAllotment, name='hostelRoomAllotment'),
    url(r'^officeOfDeanStudents/deleteHostelRoomAllotment', views.deleteHostelRoomAllotment, name='deleteHostelRoomAllotment'),
    url(r'^officeOfDeanStudents/deleteAllHostelRoomAllotment', views.deleteAllHostelRoomAllotment),
    url(r'^officeOfDeanStudents/budget_approval', views.budgetApproval),
    url(r'^officeOfDeanStudents/budget_rejection', views.budgetRejection),
    url(r'^officeOfDeanStudents/club_approval', views.clubApproval),
    url(r'^officeOfDeanStudents/club_rejection', views.clubRejection),
    url(r'^officeOfDeanStudents/budgetAllotEdit', views.budgetAllotEdit),
    url(r'^officeOfDeanStudents/budgetAllot', views.budgetAllot),
    url(r'^officeOfDeanStudents/session_approval', views.sessionApproval),
    url(r'^officeOfDeanStudents/session_rejection', views.sessionRejection),
    url(r'^officeOfDeanAcademics/$', views.officeOfDeanAcademics, name='officeOfDeanAcademics'),

    url(r'^officeOfDeanAcademics/assistantship', views.assistantship, name='assistantship'),
    url(r'^officeOfDeanAcademics/formsubmit', views.formsubmit, name='formsubmit'),
    url(r'^officeOfDeanAcademics/init_assistantship', views.init_assistantship, name='init_assistantship'),
    url(r'^officeOfDeanAcademics/scholarshipform', views.scholarshipform),
    url(r'^officeOfDeanAcademics/applications', views.applications, name='applications'),
    url(r'^officeOfDeanAcademics/courses', views.courses, name='courses'),
    url(r'^officeOfDeanAcademics/scholarship', views.scholarship, name='scholarship'),
    url(r'^officeOfDeanAcademics/semresults', views.semresults, name='semresults'),
    url(r'^officeOfDeanAcademics/thesis', views.thesis, name='thesis'),
]

FusionIIIT/applications/hostel_management/forms.py
from django import forms
from .models import HostelNoticeBoard, Hall


class HostelNoticeBoardForm(forms.ModelForm):
    class Meta:
        model = HostelNoticeBoard
        fields = ('hall', 'head_line', 'content', 'description')
       

FusionIIIT/templates/hostelmanagement/add_student.html
{% block add_student %}
<h3 align="center"> Student Room Allotment Application Form </h3><br><br>
<!-- <form action="{%url 'office_module:teaching_form' %}" method ="POST"> -->
<form action={% url 'hostelmanagement:edit_student_room' %} method ="POST" id="edit_student_form">
   {% comment %}The add a new skill Accordian starts here!{% endcomment %}
   <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">
        {% csrf_token %}
        
       <div class="three fields">
           <div class="six wide field">
               <label>Roll no.</label>
               {% comment %} <input value="" class="ui large input" name="roll_no" required onkeypress="return isNumberKey(event)"> {% endcomment %}
               <select class="ui search fluid dropdown" name="roll_no" required>
                   <option value="">Select</option>
                   {% for i, students in halls_student.items %}
                        {% for st in students %}
                        <option value="{{st.id.user.username}}">{{st.id.user.username}}</option>
                        {% endfor %}
                   {%endfor%}
               </select>
           </div>


           <div class="six wide field">
                <label>Room no.</label>
                {% comment %} <input value="" class="ui large input" name="room_no" required> {% endcomment %}
                <select class="ui search fluid dropdown" name="hall_room_no" required>
                   <option value="">Select</option>
                   
                   {% for room in room_avail%}
                        <option value="{{room.hall}}-{{room.block_no}}-{{room.room_no}}">{{room.hall.hall_id}}-{{room.block_no}}-{{room.room_no}}</option>
                   {% endfor %}
               </select>
           </div>


           
       </div>

       <div class="field">
           <button class="ui primary button right floated" type="submit" onclick="checkInputs('edit_student_form')">
               Submit
           </button>
       </div>
   </div>
</form>

<br>
<br>
<div class="ui divider"></div>

 {% endblock %}

FusionIIIT/templates/hostelmanagement/alloted_hostel_room.html
{% block alloted_hostel_room %}
<div class="ui secondary menu">

    <div class="ui floating dropdown labeled icon button">
    <i class="home icon"></i>
    <span class="text">Select Hall</span>
        <div class="menu">
        {% for hall in all_hall %}
            <a class="{% if hall.hall_id == current_hall %}item active{% else %}item{% endif %}" data-tab={{hall.hall_id}}>
                Hall {{hall.hall_id.4}}
            </a>
        {% endfor %}
        </div>
    </div>

{% if user in hall_caretaker %}
<div class="right menu">
    <a class="item" data-tab="add_student">
        <i class="edit icon"></i>Edit Student
    </a>
</div>
{% endif %}

<div class="center menu">
    {% if user in hall_caretaker%}
      <a class="item" data-tab="edit_by_sheet">
          <i class="edit icon"></i>Upload Sheet
      </a>
    {% endif %}
</div>

</div>


{% for hall in all_hall %}
    <div class="{% if hall.hall_id == current_hall %}ui active tab{% else %}ui tab{% endif %}" data-tab={{hall.hall_id}}>
        <div class="textLoader" style="max-height: 64vh; overflow-y: auto; overflow-x: hidden;">
            {% block {{hall.hall_id}} %}
                {% include 'hostelmanagement/halls.html' with hall_id=hall.hall_id %}
            {% endblock %}
        </div>
    </div>
{% endfor %}


 <div class="ui tab" data-tab="add_student">
    <div class="ui vertical segment">
        {% block add_student %}
            {% include 'hostelmanagement/add_student.html' %}
        {% endblock %}
    </div>
</div> 

<div class="ui tab" data-tab="edit_by_sheet">
    <div class="ui vertical segment">
        {% block room_upload %}
            {% include 'hostelmanagement/upload_student_rooms.html' %}
        {% endblock %}
    </div>
</div>

<br>
<br>

<div class="ui divider"></div>

{% endblock %}

FusionIIIT/templates/hostelmanagement/hall_staff_edit.html
{% block hall_staff_edit %}
<h3 align="center"> HALL STAFF EDIT </h3><br><br>
<form action="{% url 'hostelmanagement:staff_edit_schedule' %}" method ="POST" id="hall_staff_edit_form">
   <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">
        {% csrf_token %}
        
       <div class="two fields">
           <div class="six wide field">
               <label>Staff Type</label>
               <select class="ui search fluid dropdown" name="staff_type" required>
                   <option value="">Select</option>
                   <option value="Caretaker">Caretaker</option>
                   <option value="Gaurd">Gaurd</option>
               </select>
           </div>
        </div>
    
        <div class="two fields">
           <div class="six wide field">
                <label>Staff Name</label>
                <div class="ui fluid search selection dropdown">
                    <input name="Staff_name"  type="hidden">
                    <i class="dropdown icon"></i>
                    <div class="default text">Select</div>
                    <div class="menu">
                        {% for staff in staff%}
                        <div class="item" data-value={{ staff.pk }}>
                        {{staff.id.user.first_name}} {{staff.id.user.last_name}}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

           <div class="six wide field">
               <label>Day</label>
               <select class="ui search fluid dropdown" name="day" required>
                   <option value="">Select</option>
                   <option value="Monday">Monday</option>
                   <option value="Tuesday">Tuesday</option>
                   <option value="Wednesday">Wednesday</option>
                   <option value="Thursday">Thursday</option>
                   <option value="Friday">Friday</option>
                   <option value="Saturday">Saturday</option>
                   <option value="Sunday">Sunday</option>
               </select>
           </div>
           
       </div>
       
       <div class="two fields">
            <div class="six wide field">
                <label>Start Time</label>
                <input type="time"  class="ui large input"  name="start_time" required>
           </div>
            <div class="six wide field">
                <label>End Time</label>
                <input type="time"  class="ui large input"  name="end_time" required>
           </div>

       </div>

       <div class="field">
           <button class="ui primary button right floated" type="submit" onclick="checkInputs('hall_staff_edit_form'); return checkTimes();">
               Submit
           </button>
       </div>
   </div>
</form>

<br>
<br>
<div class="ui divider"></div>
<script type="text/javascript">
   
   function isNumberKey(evt){
   var charCode = (evt.which) ? evt.which : event.keyCode
   if (charCode > 31 && (charCode < 48 || charCode > 57))
       return false;
   return true;
}

</script>

 {% endblock %} 

FusionIIIT/templates/hostelmanagement/hall_staffs.html
{% load custom_tags %}
{% block {{hall.hall_id}} %}
{% comment %} <table class="ui fixed sortable celled table"> {% endcomment %}
<table class="ui fixed sortable table">
    <thead>
    <tr>
        <th class="four wide">Staff Name</th>
        <th class="four wide">Caretaker/Guard</th>
        <th class="three wide">Day</th>
        <th class="three wide">Start Time</th>
        <th class="three wide">End Time</th>
        {% if user in hall_caretaker%}
            {% ifequal current_hall hall_id %}
                <th class="two wide">Delete</th>
            {% endifequal %}
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for staff in hall_staffs|get_hall_no:hall_id %}
    <tr>
        <td>
            {{ staff.staff_id.id.user.first_name }} {{ staff.staff_id.id.user.last_name }}
        </td>

        <td>
            {{ staff.staff_type }}
        </td>

        <td>
            {{ staff.day }}
        </td>

        <td>
            {{ staff.start_time }}
        </td>

        <td>
            {{ staff.end_time }}
        </td>
        {% if user in hall_caretaker%}
            {% ifequal current_hall hall_id %}
                <td>
                    <form method="post"  action="{% url 'hostelmanagement:staff_delete_schedule' %}" class="ui form" role="form">
                    {% csrf_token %}
                    <button class="mini ui button" type="submit" value="{{ staff.staff_id.pk }}" name="dlt_schedule" onclick="return confirm('Are you sure you want to DELETE this staff schedule?');"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                                                    width="20" height="20" viewBox="0 0 24 24" style=" fill:#000;"><path d="M 10 2 L 9 3 L 4 3 L 4 5 L 7 5 L 17 5 L 20 5 L 20 3 L 15 3 L 14 2 L 10 2 z M 5 7 L 5 20 C 5 21.1 5.9 22 7 22 L 17 22 C 18.1 22 19 21.1 19 20 L 19 7 L 5 7 z"></path></svg></button>
                    </form>
                </td>
            {% endifequal %}
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

FusionIIIT/templates/hostelmanagement/notice_board.html
{% load custom_tags %}
{% block {{hall.hall_id}} %}

    {% for notice in hall_notices|get_hall_no:hall_id %}

    <div class="ui secondary segment">
        <div class="ui segment" >
            <h2 class="ui center aligned header">{{notice.head_line|truncatechars_html:50}}</h2>
            <h4 style="text-align:right;">{{notice.posted_by.user.first_name}} {{notice.posted_by.user.last_name}} - {{notice.posted_by.user.username}}</h4>

            <div class="ui styled accordion">
                <div class="title">
                        <i class="dropdown icon"></i>
                        More
                    </div>

                
                <div class="content">
                    <h3 style="color:grey;">Description</h3>
                    <h4 class="transition hidden" style="color:black;">{{notice.description}}</h4>
                    <h4 class="ui dividing header"><a href="..\media\{{notice.content}}">Content Link</a></h4>
                </div>
                
            </div>
            <br>
            
            {% if user in hall_caretaker or hall_warden %}
                {% ifequal current_hall notice.hall.hall_id %}
                    <form method="post"  action="{% url 'hostelmanagement:delete_notice' %}" class="ui form" role="form">
                        {% csrf_token %}
                        <button class="mini ui negative basic button" type="submit" value="{{ notice.pk }}" name="dlt_notice" style="margin-left:90%" onclick="return confirm('Are you sure you want to DELETE this notice?');"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                                                        width="20" height="20" viewBox="0 0 24 24" style=" fill:#000;"><path d="M 10 2 L 9 3 L 4 3 L 4 5 L 7 5 L 17 5 L 20 5 L 20 3 L 15 3 L 14 2 L 10 2 z M 5 7 L 5 20 C 5 21.1 5.9 22 7 22 L 17 22 C 18.1 22 19 21.1 19 20 L 19 7 L 5 7 z"></path></svg></button>
                    </form>
                {% endifequal %}
            {% endif %}
        </div>
      </div>
    
    {% endfor %}

{% endblock %}

FusionIIIT/templates/hostelmanagement/notice_form.html
{% block notice_form %}
<form method="POST" action="{% url 'hostelmanagement:notice_board' %}" class="ui form" role="form" enctype="multipart/form-data" id='notice_form'>
                <div class="ui active accordion field">
                    <div class="title">
                        <i class="icon dropdown"></i>
                        Create a new Notice!
                    </div>
                    {{ form.non_field_errors }}
                    <div class="active content">
                        <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">
                          {% csrf_token %}
                            
                                <div class="field">
                                    <label for="{{ form.hall.id_for_label }}">
                                        Hall
                                    </label>
                                    <select class="ui dropdown" name="hall" required>
                                        <option selected disabled value="">Select Hall No</option>
                                        {% for hall in all_hall %}
                                            <option value={{hall.pk}}>{{hall.hall_name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="field">
                                  {{ form.head_line.errors }}
                                    <label for="{{ form.head_line.id_for_label }}">
                                        HeadLine
                                    </label>
                                    <input type="text" name="head_line" required="required" value="{{ form.head_line }}"  class="ui large input">
                                </div>
                       
                                <div class="field">
                                    {{ form.content.errors }}
                                    <label  for="{{ form.content.id_for_label }}">
                                    Content</label>
                                    <input type='file' name='content' value={{ form.content }}>
                                </div>

                                <div class="field">
                                    {{ form.description.errors }}
                                    <label for="{{ form.description.id_for_label }}">
                                        Description
                                    </label>                                    
                                    <textarea name="description">{{ form.description }}</textarea>                                     
                                </div>

                            
                            <div class="two fields">
                              <div class="four wide field">
                                  <label><br></label>
                                  <button class="ui fluid large primary button" type="submit" onclick="checkInputs('notice_form')">
                                      Submit
                                  </button>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
{% endblock %}

FusionIIIT/templates/hostelmanagement/upload_student_rooms.html
{% block room_upload %}

<h3 align="center"> Student Rooms Upload Form </h3><br><br>

<form action="{% url 'hostelmanagement:edit_student_rooms_sheet' %}" method ="POST" enctype="multipart/form-data">
   
   <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">
        {% csrf_token %}
        <div class="field">
            <h4 class="ui blue header">Note : Provide the data in Excel Sheet(xls not xlsx) in following format:</h4>
            ROLL NO. | HALL NO. | ROOM NO.
            <h4 class="ui dividing header"><a href="..\media\hostel_management\worker_report.xls">Download</a> the sample Excel, fill the data accordingly and then upload the same</h4>
        </div>
            
       <div class="field">
        <label for="file">Upload File (.xls)</label>
           <input type='file' name= "upload_rooms" accept=".xls" required> 

           <button class="ui primary button right floated" type="submit">
               Submit
           </button>
       </div>
   </div>
</form>

<br>
<br>
<div class="ui divider"></div>

{% endblock %}

FusionIIIT/templates/hostelmanagement/view_report.html
{% block view_report %}
<form method="GET" action="{% url 'hostelmanagement:pdf' %}" class="ui form" role="form" enctype="multipart/form-data">
  <div class = "field">
  
        <label>Total Months</label>
        <input type="number"  class="ui input"  name="months" placeholder="Months"required style="width: 20%">

        <button class="ui primary basic button" type="submit">
            Download as PDF
        </a></button>
        
  </div>
  </form>
 <table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2%;
            padding-right: 5%;
            padding-top: 1%;
            padding-bottom: 1.5%;
            margin: auto;">
    <thead>
    <tr>

        <th class="one wide column">
           Worker ID
        </th>

        <th class="six wide column">
            Name
        </th>

        <th class="four wide column">
            Month/Year
        </th>

        <th class="four wide column">
            Today Working Days
        </th>
        <th class="two wide column">
           Total Absent
        </th>
        <th class="four wide column">
           Remark
        </th>


    </tr>
    </thead>

    <tbody>
    {% for worker in worker_report %}
    <tr>
        <td>
            {{worker.worker_id}}
        </td>

        <td>
            {{worker.worker_name}}
        </td>

        <td>
            {{worker.month}}/{{worker.year}}
        </td>

        <td>
            {{worker.total_day}}
        </td>
        <td>
            {{worker.absent}}
        </td>
        <td>
            {{worker.remark}}
        </td>

    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}