FusionIIIT/Fusion/urls.py
import notifications.urls
import debug_toolbar
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls')),
    url(r'^aims/', include('applications.academic_information.urls')),
    url(r'^notifications/', include('applications.notifications_extension.urls')),
    url(r'^estate/', include('applications.estate_module.urls')),
    url(r'^dep/', include('applications.department.urls')),
    url(r'^programme_curriculum/',include('applications.programme_curriculum.urls')),
    url(r'^iwdModuleV2/', include('applications.iwdModuleV2.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^research_procedures/', include('applications.research_procedures.urls')),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^eis/', include('applications.eis.urls')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^purchase-and-store/', include('applications.ps1.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^establishment/', include('applications.establishment.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^counselling/', include('applications.counselling_cell.urls')),
    url(r'^hostelmanagement/', include('applications.hostel_management.urls')),
    url(r'^income-expenditure/', include('applications.income_expenditure.urls')),
    url(r'^hr2/', include('applications.hr2.urls')),
    url(r'^recruitment/', include('applications.recruitment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FusionIIIT/applications/programme_curriculum/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.contrib import admin

app_name = 'programme_curriculum'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.programme_curriculum, name='programme_curriculum'),

    path('programmes/', views.view_all_programmes, name='view_all_programmes'),
    path('working_curriculums/', views.view_all_working_curriculums, name='view_all_working_curriculums'),
    path('curriculums/<programme_id>/', views.view_curriculums_of_a_programme, name='view_curriculums_of_a_programme'),
    path('curriculum_semesters/<curriculum_id>/', views.view_semesters_of_a_curriculum, name='view_semesters_of_a_curriculum'),
    path('semester/<semester_id>/', views.view_a_semester_of_a_curriculum, name='view_a_semester_of_a_curriculum'),
    path('courseslot/<courseslot_id>/', views.view_a_courseslot, name='view_a_courseslot'),
    path('courses/', views.view_all_courses, name='view_all_courses'),
    path('course/<course_id>/', views.view_a_course, name='view_a_course'),
    path('disciplines/', views.view_all_discplines, name='view_all_discplines'),
    path('batches/', views.view_all_batches, name='view_all_batches'),

    path('admin_programmes/', views.admin_view_all_programmes, name='admin_view_all_programmes'),
    path('admin_working_curriculums/', views.admin_view_all_working_curriculums, name='admin_view_all_working_curriculums'),
    path('admin_curriculums/<programme_id>/', views.admin_view_curriculums_of_a_programme, name='admin_view_curriculums_of_a_programme'),
    path('admin_curriculum_semesters/<curriculum_id>/', views.admin_view_semesters_of_a_curriculum, name='admin_view_semesters_of_a_curriculum'),
    path('admin_semester/<semester_id>/', views.admin_view_a_semester_of_a_curriculum, name='admin_view_a_semester_of_a_curriculum'),
    path('admin_courseslot/<courseslot_id>/', views.admin_view_a_courseslot, name='admin_view_a_courseslot'),
    path('admin_courses/', views.admin_view_all_courses, name='admin_view_all_courses'),
    path('admin_course/<course_id>/', views.admin_view_a_course, name='admin_view_a_course'),
    path('admin_disciplines/', views.admin_view_all_discplines, name='admin_view_all_discplines'),
    path('admin_batches/', views.admin_view_all_batches, name='admin_view_all_batches'),
    
    path('admin_add_programme/', views.add_programme_form, name='add_programme_form'),
    path('admin_add_discipline/', views.add_discipline_form, name='add_discipline_form'),
    path('admin_add_curriculum/', views.add_curriculum_form, name='add_curriculum_form'),
    path('admin_add_course/', views.add_course_form, name='add_course_form'),
    path('admin_add_courseslot/', views.add_courseslot_form, name='add_courseslot_form'),
    path('admin_add_course/', views.add_course_form, name='add_course_form'),
    path('admin_add_batch/', views.add_batch_form, name='add_batch_form'),

    path('admin_update_course/<course_id>/', views.update_course_form, name='update_course_form'),
    path('admin_edit_curriculum/<curriculum_id>/', views.edit_curriculum_form, name='edit_curriculum_form'),
    path('admin_edit_programme/<programme_id>/', views.edit_programme_form, name='edit_programme_form'),
    path('admin_edit_courseslot/<courseslot_id>/', views.edit_courseslot_form, name='edit_courseslot_form'),
    path('admin_delete_courseslot/<courseslot_id>/', views.delete_courseslot, name='delete_courseslot'),
    path('admin_edit_batch/<batch_id>/', views.edit_batch_form, name='edit_batch_form'),
    path('admin_edit_discipline/<discipline_id>/', views.edit_discipline_form, name='edit_discipline_form'),
    path('admin_instigate_semester/<semester_id>/', views.instigate_semester, name='instigate_semester'),
    path('admin_replicate_curriculum/<curriculum_id>/', views.replicate_curriculum, name='replicate_curriculum'),
]

FusionIIIT/applications/programme_curriculum/views.py
from django.db.models.query_utils import Q
from django.http import request
from django.shortcuts import get_object_or_404, render, HttpResponse
from django.http import HttpResponse, HttpResponseRedirect
import itertools
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Programme, Discipline, Curriculum, Semester, Course, Batch, CourseSlot
from .forms import ProgrammeForm, DisciplineForm, CurriculumForm, SemesterForm, CourseForm, BatchForm, CourseSlotForm, ReplicateCurriculumForm
from .filters import CourseFilter, BatchFilter, CurriculumFilter

# from applications.academic_information.models import Student
from applications.globals.models import (DepartmentInfo, Designation,
                                         ExtraInfo, Faculty, HoldsDesignation)

# ------------module-functions---------------#

@login_required(login_url='/accounts/login')
def programme_curriculum(request):
    """
    This function is used to Differenciate acadadmin and all other user.

    @param:
        request - contains metadata about the requested page

    @variables:
        user_details - Gets the information about the logged in user.
        des - Gets the designation about the looged in user.
    """
    user_details = ExtraInfo.objects.get(user = request.user)
    des = HoldsDesignation.objects.all().filter(user = request.user).first()
    if str(des.designation) == "student" or str(des.designation) == "Associate Professor" or str(des.designation) == "Professor" or str(des.designation) == "Assistant Professor" :
        return HttpResponseRedirect('/programme_curriculum/programmes/')
    elif str(request.user) == "acadadmin" :
        return HttpResponseRedirect('/programme_curriculum/admin_programmes')
    
    return HttpResponseRedirect('/programme_curriculum/programmes/')



# ------------all-user-functions---------------#



def view_all_programmes(request):
    """
    This function is used to display all the programmes offered by the institute.
    @variables:
        ug - UG programmes
        pg - PG programmes
        phd - PHD programmes 
    """
    ug = Programme.objects.filter(category='UG')
    pg = Programme.objects.filter(category='PG')
    phd = Programme.objects.filter(category='PHD')


    return render(request, 'programme_curriculum/view_all_programmes.html', {'ug': ug, 'pg': pg, 'phd': phd})


def view_curriculums_of_a_programme(request, programme_id):
    """
    This function is used to Display Curriculum of a specific Programmes.

    @param:
        programme_id - Id of a specific programme
        
    @variables:
        curriculums - Curriculums of a specific programmes
        batches - List of batches for curriculums
        working_curriculum - Curriculums that are affective
        past_curriculum - Curriculums thet are obsolete
    """
    program = get_object_or_404(Programme, Q(id=programme_id))
    curriculums = program.curriculums

    curriculumfilter = CurriculumFilter(request.GET, queryset=curriculums)

    curriculums = curriculumfilter.qs

    working_curriculums = curriculums.filter(working_curriculum=1)
    past_curriculums = curriculums.filter(working_curriculum=0)

    return render(request,'programme_curriculum/view_curriculums_of_a_programme.html', {'program': program, 'past_curriculums': past_curriculums, 'working_curriculums': working_curriculums, 'curriculumfilter': curriculumfilter})


def view_all_working_curriculums(request):
    """ views all the working curriculums offered by the institute """
    
    curriculums = Curriculum.objects.filter(working_curriculum=1)

    curriculumfilter = CurriculumFilter(request.GET, queryset=curriculums)

    curriculums = curriculumfilter.qs
    return render(request,'programme_curriculum/view_all_working_curriculums.html',{'curriculums':curriculums, 'curriculumfilter': curriculumfilter})



def view_semesters_of_a_curriculum(request, curriculum_id):
    """
    This function is used to Display all Semester of a Curriculum.

    @param:
        curriculum_id - Id of a specific curriculum
        
    @variables:
        transpose_semester_slots - semester_slots 2D list is transpose for viewing in HTML <table>.
        semester_credits - Total Credits for each semester.
    """
    curriculum = get_object_or_404(Curriculum, Q(id=curriculum_id))
    semesters = curriculum.semesters
    semester_slots = []
    for sem in semesters:
        a = list(sem.courseslots)
        semester_slots.append(a)

    max_length = 0
    for course_slots in semester_slots:
        max_length = max(max_length, len(course_slots))

    for course_slots in semester_slots:
        course_slots += [""] * (max_length - len(course_slots))

    semester_credits = []

    for semester in semesters:
        credits_sum = 0
        for course_slot in semester.courseslots:
            max_credit = 0
            courses = course_slot.courses.all()
            for course in courses:
                max_credit = max(max_credit, course.credit)
            credits_sum = credits_sum + max_credit
        semester_credits.append(credits_sum)

    print (semester_credits)
    
    transpose_semester_slots = list(zip(*semester_slots))

    return render(request, 'programme_curriculum/view_semesters_of_a_curriculum.html', {'curriculum': curriculum, 'semesters': semesters, 'semester_slots': transpose_semester_slots, 'semester_credits': semester_credits})


def view_a_semester_of_a_curriculum(request, semester_id):
    """ views a specfic semester of a specfic curriculum """

    semester = get_object_or_404(Semester, Q(id=semester_id))
    course_slots = semester.courseslots

    return render(request, 'programme_curriculum/view_a_semester_of_a_curriculum.html', {'semester': semester, 'course_slots': course_slots})


def view_a_courseslot(request, courseslot_id):
    """ view a course slot """
    course_slot = get_object_or_404(CourseSlot, Q(id=courseslot_id))
    return render(request, 'programme_curriculum/view_a_courseslot.html', {'course_slot': course_slot})


def view_all_courses(request):
    """ views all the course slots of a specfic semester """
    courses = Course.objects.all()

    coursefilter = CourseFilter(request.GET, queryset=courses)

    courses = coursefilter.qs
    return render(request, 'programme_curriculum/view_all_courses.html', {'courses': courses, 'coursefilter': coursefilter})


def view_a_course(request, course_id):
    """ views the details of a Course """
    course = get_object_or_404(Course, Q(id=course_id))
    return render(request, 'programme_curriculum/view_a_course.html', {'course': course})


def view_all_discplines(request):
    """ views the details of a Course """

    disciplines = Discipline.objects.all()
    return render(request, 'programme_curriculum/view_all_disciplines.html', {'disciplines': disciplines})


def view_all_batches(request):
    """ views the details of a Course """

    batches = Batch.objects.all().order_by('year')

    batchfilter = BatchFilter(request.GET, queryset=batches)

    batches = batchfilter.qs

    finished_batches = batches.filter(running_batch=False)

    batches = batches.filter(running_batch=True)

    return render(request, 'programme_curriculum/view_all_batches.html', {'batches': batches, 'finished_batches': finished_batches, 'batchfilter': batchfilter})




# ------------Acad-Admin-functions---------------#


@login_required(login_url='/accounts/login')
def admin_view_all_programmes(request):
    """
    This function is used to display all the programmes offered by the institute.
    @variables:
        ug - UG programmes
        pg - PG programmes
        phd - PHD programmes 
    """    
    user_details = ExtraInfo.objects.get(user = request.user)
    des = HoldsDesignation.objects.all().filter(user = request.user).first()
    if str(des.designation) == "student" or str(des.designation) == "Associate Professor" or str(des.designation) == "Professor" or str(des.designation) == "Assistant Professor" :
        return HttpResponseRedirect('/programme_curriculum/programmes/')
    elif str(request.user) == "acadadmin" :
        pass
    
    ug = Programme.objects.filter(category='UG')
    pg = Programme.objects.filter(category='PG')
    phd = Programme.objects.filter(category='PHD')

    return render(request, 'programme_curriculum/acad_admin/admin_view_all_programmes.html', {'ug': ug, 'pg': pg, "phd": phd})


@login_required(login_url='/accounts/login')
def admin_view_curriculums_of_a_programme(request, programme_id):
    """
    This function is used to Display Curriculum of a specific Programmes.

    @param:
        programme_id - Id of a specific programme
        
    @variables:
        curriculums - Curriculums of a specific programmes
        batches - List of batches for curriculums
        working_curriculum - Curriculums that are affective
        past_curriculum - Curriculums thet are obsolete
    """    
    user_details = ExtraInfo.objects.get(user = request.user)
    des = HoldsDesignation.objects.all().filter(user = request.user).first()
    if str(des.designation) == "student" or str(des.designation) == "Associate Professor" or str(des.designation) == "Professor" or str(des.designation) == "Assistant Professor" :
        return HttpResponseRedirect('/programme_curriculum/programmes/')
    elif str(request.user) == "acadadmin" :
        pass
    
    program = get_object_or_404(Programme, Q(id=programme_id))
    curriculums = program.curriculums

    curriculumfilter = CurriculumFilter(request.GET, queryset=curriculums)

    curriculums = curriculumfilter.qs

    working_curriculums = curriculums.filter(working_curriculum=1)
    past_curriculums = curriculums.filter(working_curriculum=0)

FusionIIIT/templates/programme_curriculum/acad_admin/add_discipline_form.html
{% extends 'programme_curriculum/acad_admin/common.html' %}

{% block sidetabmenu %}
    <div class="ui medium fluid vertical pointing menu"
            style="max-width: 320px;">
        
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_programmes' %}">Programmes & Curriculums
            <i class="right floated chevron right icon"></i>
        </a>
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_working_curriculums' %}">Working Curriculums
            <i class="right floated chevron right icon"></i>
        </a>
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_discplines' %}">Discipline
            <i class="right floated chevron right icon"></i>
        </a>
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_batches' %}">Batch
            <i class="right floated chevron right icon"></i>
        </a>
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_courses' %}">Courses
            <i class="right floated chevron right icon"></i>
        </a>
    </div>
{% endblock %}

{% block content %}
<div class="ui segment" >
    <div class="header"><h1>Discipline Form</h1></div>
    <div class="ui divider"></div>
    <form class="ui large form" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <td></td>
        <td>
            <div class="ui large right floated buttons">
                <a class="ui button" href="{% url 'programme_curriculum:admin_view_all_discplines' %}">Cancel</a>
                <div class="or"></div>
                <input class="ui primary button" type="Submit" name="Submit">
            </div>
        </td>
    </form>
</div>
<div class="ui hidden divider"></div>
    <script>
        $(window).load(function() {
            $('form').get(0).reset(); //clear form data on page load
        });
    </script>

{% endblock %}

FusionIIIT/templates/programme_curriculum/acad_admin/admin_view_semesters_of_a_curriculum.html
{% extends 'programme_curriculum/acad_admin/common.html' %}

{% block sidetabmenu %}
    <div class="ui medium fluid vertical pointing menu"
            style="max-width: 320px;">
        
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_programmes' %}">Programmes & Curriculums
            <i class="right floated chevron right icon"></i>
        </a>
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_working_curriculums' %}">Working Curriculums
            <i class="right floated chevron right icon"></i>
        </a>
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_discplines' %}">Discipline
            <i class="right floated chevron right icon"></i>
        </a>
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_batches' %}">Batch
            <i class="right floated chevron right icon"></i>
        </a>
        <a class="item" href="{% url 'programme_curriculum:admin_view_all_courses' %}">Courses
            <i class="right floated chevron right icon"></i>
        </a>
    </div>
{% endblock %}

{% block content %}
<div class="ui top attached tabular large menu">
    <a class="item active" data-tab="afirst">{{ curriculum.name }} Table</a>
</div>
<div class="ui bottom attached tab segment active" data-tab="afirst">
    <div class="content">
        <div class="description"  style="overflow: auto; width: auto; max-height: auto">
            <table class="ui celled padded medium table"
                    style="text-align: center;
                        margin: auto;">
                <tbody>
                    <tr style="font-size: medium;
                        background-color: whitesmoke;">
                        <td></td>
                        <td colspan="{{ curriculum.no_of_semester }} ">
                            <h2 class="header">{{ curriculum }}</h2>
                        </td>
                    </tr>
                    {% if curriculum.batches.count > 0 %}
                    <tr style="font-size: medium;
                        background-color: whitesmoke;">
                        <td></td>
                        <td colspan="{{ curriculum.no_of_semester }}">
                            <h4 class="header">
                                Batches:&nbsp;&nbsp;&nbsp;&nbsp;
                                {% for batch in curriculum.batches.all %}
                                    {{ batch }},&nbsp;&nbsp;&nbsp;&nbsp;
                                {% endfor %}
                            </h4>
                        </td>
                    </tr>
                    {% endif %}
                    <tr style="font-size: medium;
                            background-color: whitesmoke;">
                        <td></td>
                        {% for semester in semesters %}
                        <td><a href="{% url 'programme_curriculum:admin_view_a_semester_of_a_curriculum' semester.id %}"><B>Semester<br>{{ semester.semester_no }}</B></a></td>
                        {% endfor %}
                    </tr>
                
                    {% for course_slot in semester_slots %}
                    <tr class="compact ui celled small table"
                        style="text-align: center;
                        margin: auto;">
                        <td></td>
                        {% for slot in course_slot %}
                            {% if slot != "" %}
                                <td colspan="1">
                                    {% if slot.courses.count != 1 %}
                                        <a href="{% url 'programme_curriculum:admin_view_a_courseslot' slot.id %}">{{ slot.name }}</a>
                                    {% else %}
                                        {% for course in slot.courses.all %}
                                            <a href="{% url 'programme_curriculum:admin_view_a_courseslot' slot.id %}"><p>{{ course }}<br>(L: {{ course.lecture_hours }}, T: {{ course.tutorial_hours }}, C: {{ course.credit }})</p></a>
                                        {% endfor %}
                                    {% endif %}
                                </td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                    <tr class="compact ui celled small table"
                        style="text-align: center;
                            margin: auto;">
                        <td>Start Date</td>
                        {% for semester in semesters %}
                            {% if semester.start_semester == None %}
                                <td></td>
                            {% else %}
                                <td>{{ semester.start_semester }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    <tr class="compact ui celled small table"
                        style="text-align: center;
                            margin: auto;">
                        <td>End Date</td>
                        {% for semester in semesters %}
                            {% if semester.end_semester == None %}
                                <td></td>
                            {% else %}
                                <td>{{ semester.end_semester }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    <tr class="compact ui celled small table"
                        style="text-align: center;
                            margin: auto;">
                        <td>Total Credits</td>
                        {% for total_credits in semester_credits %}
                            <td>{{ total_credits }}</td>
                        {% endfor %}
                    </tr>
                    <tr class="compact ui celled small table"
                        style="text-align: center;
                            margin: auto;">
                        <td>Instigated</td>
                        {% for semester in semesters %}
                            {% if semester.instigate_semester == True %}
                                <td class="positive">
                                    <i class="icon checkmark"></i>Yes
                                </td>
                            {% else %}
                                <td class="warning">
                                    <i class="attention icon"></i>Not Yet
                                </td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $("table").tablesorter({
        headers: {
          '.first-name' : {
          sorter: false
        }
      }
    });
</script>
{% endblock %}
{% block rightcontent %}
<br>
<br>
<div class="ui center aligned segment">
    <div class="fluid ui large labeled icon floating link dropdown teal button">
        <i class="options icon"></i>
        OPTIONS
        <div class="ui left menu">
            <div class="header">
                Curriculum
            </div>
            <div class="ui divider"></div>
            <div class="ui fitted item">
                <a class="fluid ui large positive animated button"
                    href="{% url 'programme_curriculum:edit_curriculum_form' curriculum.id %}"
                    type="Submit" name="Submit">
                    <div class="visible content">EDIT CURRICULUM</div>
                    <div class="hidden content">
                    <i class="edit icon"></i>
                    </div>
                </a>
            </div>
            <div class="ui fitted item">
                <div class="fluid ui large secondary animated button">
        
                    <i class="dropdown icon"></i>
                    <div class="visible content">INSTIGATE SEMESTER</div>
                    <div class="hidden content">
                        <i class="bell icon"></i>
                    </div>
                </div>
                <div class="ui vertical left menu">
                    {% for semester in semesters %}
                        <a class="item" 
                        href="{% url 'programme_curriculum:instigate_semester' semester.id %}?curriculum_id={{ semester.curriculum.id }}"
                        type="Submit" name="Submit"><i class="bell icon"></i>Semester {{ semester.semester_no }}</a>
                    {% endfor %}
                </div>
            </div>
            <div class="ui fitted item">
                <div class="fluid ui large primary animated button">
                    
                    <i class="dropdown icon"></i>
                    <div class="visible content">ADD COURSE SLOT</div>
                    <div class="hidden content">
                        <i class="add icon"></i>
                    </div>
                </div>
                <div class="ui vertical left menu">
                    {% if semesters.count < 1 %}
                        <div class="item">No Semesters for this Curriculum</div>
                    {% else %}
                        {% for semester in semesters %}
                            <a class="item" 
                            href="{% url 'programme_curriculum:add_courseslot_form' %}?semester_id={{ semester.id }}&curriculum_id={{ curriculum.id }}"
                            type="Submit" name="Submit"><i class="add icon"></i>Semester {{ semester.semester_no }}</a>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="header">
                Batches
            </div>
            <div class="ui divider"></div>
            <div class="ui fitted item">
                <a class="fluid ui large primary animated button"
                    href="{% url 'programme_curriculum:add_batch_form' %}?curriculum_id={{ curriculum.id }}"
                    type="Submit" name="Submit" target="_blank" rel="noopener">
                    <div class="visible content">NEW BATCH</div>
                    <div class="hidden content">
                    <i class="add icon"></i>
                    </div>
                </a>
            </div>
            <div class="ui fitted item">
                <div class="fluid ui large positive animated button">
        
                    <i class="dropdown icon"></i>
                    <div class="visible content">EDIT BATCH</div>
                    <div class="hidden content">
                        <i class="edit icon"></i>
                    </div>
                </div>
                <div class="ui left vertical menu">
                    {% if curriculum.batches.count < 1 %}
                        <div class="item">No batches linked to this Curriculum</div>
                    {% else %}
                        {% for batch in curriculum.batches %}
                            <a class="item" 
                            href="{% url 'programme_curriculum:edit_batch_form' batch.id %}"
                            type="Submit" name="Submit" target="_blank" rel="noopener"><i class="edit icon"></i>{{ batch }}</a>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="ui fitted item">
                <div class="fluid ui large secondary animated button">
        
                    <i class="dropdown icon"></i>
                    <div class="visible content">LINK BATCH</div>
                    <div class="hidden content">
                        <i class="tag icon"></i>
                    </div>
                </div>
                <div class="ui vertical left menu">
                    {% if all_batches.count < 1 %}
                        <div class="item">No other batches avaliable</div>
                    {% else %}
                        {% for a_batch in all_batches %}
                            <a class="item" 
                            href="{% url 'programme_curriculum:edit_batch_form' a_batch.id %}?curriculum_id={{ curriculum.id }}"
                            type="Submit" name="Submit" target="_blank" rel="noopener"><i class="tag icon"></i>{{ a_batch }}</a>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}