FusionIIIT/Fusion/urls.py
import notifications.urls
import debug_toolbar
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls')),
    url(r'^aims/', include('applications.academic_information.urls')),
    url(r'^notifications/', include('applications.notifications_extension.urls')),
    url(r'^estate/', include('applications.estate_module.urls')),
    url(r'^dep/', include('applications.department.urls')),
    url(r'^programme_curriculum/',include('applications.programme_curriculum.urls')),
    url(r'^iwdModuleV2/', include('applications.iwdModuleV2.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^research_procedures/', include('applications.research_procedures.urls')),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^eis/', include('applications.eis.urls')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^purchase-and-store/', include('applications.ps1.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^establishment/', include('applications.establishment.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^counselling/', include('applications.counselling_cell.urls')),
    url(r'^hostelmanagement/', include('applications.hostel_management.urls')),
    url(r'^income-expenditure/', include('applications.income_expenditure.urls')),
    url(r'^hr2/', include('applications.hr2.urls')),
    url(r'^recruitment/', include('applications.recruitment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FusionIIIT/applications/estate_module/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.estate, name="estate_module_home"),
    #new
    path('new/building', views.newBuilding, name="new_building"),
    path('new/work', views.newWork, name="new_work"),
    path('new/subWork', views.newSubWork, name="new_subWork"),
    path('new/inventoryType', views.newInventoryType, name="new_inventoryType"),
    path('new/inventory_consumable', views.newInventoryConsumable,
         name="new_inventory_consumable"),
    path('new/inventory_non_consumable', views.newInventoryNonConsumable,
         name="new_inventory_non_consumable"),

    #edit
    path('edit/building/<building_id>', views.editBuilding, name="edit_building"),
    path('edit/work/<work_id>', views.editWork, name="edit_work"),
    path('edit/subWork/<subWork_id>', views.editSubWork, name="edit_subWork"),
    path('edit/inventoryType/<inventoryType_id>',
         views.editInventoryType, name="edit_inventoryType"),
    path('edit/inventory_consumable/<inventory_consumable_id>',
         views.editInventoryConsumable, name="edit_inventory_consumable"),
    path('edit/inventory_non_consumable/<inventory_non_consumable_id>',
         views.editInventoryNonConsumable, name="edit_inventory_non_consumable"),

    #delete
    path('delete/building/<building_id>',
         views.deleteBuilding, name="delete_building"),
    path('delete/work/<work_id>', views.deleteWork, name="delete_work"),
    path('delete/subWork/<subWork_id>',
         views.deleteSubWork, name="delete_subWork"),
    path('delete/inventoryType/<inventoryType_id>', views.deleteInventoryType,
         name="delete_inventoryType"),
    path('delete/inventory_consumable/<inventory_consumable_id>',
         views.deleteInventoryConsumable, name="delete_inventory_consumable"),
    path('delete/inventory_non_consumable/<inventory_non_consumable_id>',
         views.deleteInventoryNonConsumable, name="delete_inventory_non_consumable"),

     #verify
     # path('verify_building/<building_id>',views.verifyBuilding,name="verify_building")
]

FusionIIIT/applications/estate_module/models.py
from django.conf import settings
from django.db import models

# Create your models here.


class Building(models.Model):
    """
    Details of the building
    @fields-
        name: name of the building
        dateIssued: date when the building was issued
        dateConstructionStarted: date when construction of building was started
        dateComstructionCompleted: date when construction of building was completed
        dateOperational: date when building became operational
        status: status of the building if it's work is on time or delayed
        area: total area of the building
        constructionCostEstimated: estimated cost of construction of building
        constructionCostActual: actual cost of construction of building
        numRooms: number of rooms in building
        numWashrooms: number of washrooms in building
        remarks: remarks for the building
        verified: tells building is verified or not
    """
    ON_SCHEDULE = 'OS'
    DELAYED = 'DL'
    STATUS_CHOICES = [
        (ON_SCHEDULE, 'On Schedule'),
        (DELAYED, 'Delayed'),
    ]
    name = models.CharField(max_length=100)
    dateIssued = models.DateField()
    dateConstructionStarted = models.DateField(null=True, blank=True)
    dateConstructionCompleted = models.DateField(null=True, blank=True)
    dateOperational = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=2, choices=STATUS_CHOICES, default=ON_SCHEDULE)
    area = models.IntegerField(null=True, blank=True)
    constructionCostEstimated = models.IntegerField(null=True, blank=True)
    constructionCostActual = models.IntegerField(null=True, blank=True)
    numRooms = models.IntegerField(null=True, blank=True)
    numWashrooms = models.IntegerField(null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)
    verified = models.BooleanField(default=False)

    def works(self):
        works_all = self.work_set.all()
        workList = [
            (Work.MAINTENANCE_WORK, 'Maintenance',
             works_all.filter(workType=Work.MAINTENANCE_WORK)),
            (Work.CONSTRUCTION_WORK, 'Construction',
             works_all.filter(workType=Work.CONSTRUCTION_WORK))
        ]
        return workList

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class Work(models.Model):

    """
        Tells about the works
        @fields-
            name: name for the work
            workType: type of the work
            building: in which building work is done
            contractorName: nsme of the contractor who is doing the work
            status: status of the work
            dateIssued: date when the work was issued
            dateStarted: date when work was started
            dateCompleted: date when work was completed
            costEstimated: estimated cost of the work
            costActual: actual cost of the work
            remarks: remarks for the work
            verified: work is verified or not
    """

    CONSTRUCTION_WORK = 'CW'
    MAINTENANCE_WORK = 'MW'
    WORK_CHOICES = [
        (CONSTRUCTION_WORK, 'Construction'),
        (MAINTENANCE_WORK, 'Maintenance'),
    ]

    ON_SCHEDULE = 'OS'
    DELAYED = 'DL'

    STATUS_CHOICES = [
        (ON_SCHEDULE, 'On Schedule'),
        (DELAYED, 'Delayed'),
    ]

    name = models.CharField(max_length=100)
    workType = models.CharField(
        max_length=2, choices=WORK_CHOICES, default=MAINTENANCE_WORK)
    building = models.ForeignKey(
        Building, on_delete=models.CASCADE, null=True, blank=True)
    contractorName = models.CharField(max_length=100)
    status = models.CharField(
        max_length=2, choices=STATUS_CHOICES, default=ON_SCHEDULE)
    dateIssued = models.DateField()
    dateStarted = models.DateField(null=True, blank=True)
    dateCompleted = models.DateField(null=True, blank=True)
    costEstimated = models.IntegerField(null=True, blank=True)
    costActual = models.IntegerField(null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)
    verified = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class SubWork(models.Model):
    """
        Details about the subWork
        @field-
            name: name of the subWork
            work: work under which the subWork is going
            dateIssued: date when the subwork was issued
            dateStarted: date when the subwork was started
            dateCompleted: date when the subwork was completed
            costEstimated: estimated cost of subwork
            costActual: actual cost of subwork
            remarks: remarks for the subWork
    """
    name = models.CharField(max_length=100)
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    dateIssued = models.DateField()
    dateStarted = models.DateField(null=True, blank=True)
    dateCompleted = models.DateField(null=True, blank=True)
    costEstimated = models.IntegerField(null=True, blank=True)
    costActual = models.IntegerField(null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.work.name + ' - ' + self.name


class InventoryType(models.Model):
    """
        Details about different type of inventory
        @fields-
            name: name of the inventory
            rate: rate of the item in inventory
            manufacturer: manufacturer of the item present in inventory
            model: model of the item present in inventory
            remarks: remarks for the item present in inventory
    """
    name = models.CharField(max_length=100)
    rate = models.IntegerField()
    manufacturer = models.CharField(max_length=100, null=True, blank=True)
    model = models.CharField(max_length=100, null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class InventoryCommon(models.Model):
    """
        Details about the common inventory
        @field-
            inventoryType: type of inventory
            building: building where inventory is present
            work: work associated with inventory
            quantity: quantity of the inventory
            dateOrdered: ordered date
            dateRecieved: recieved date
            remarks: remarks for the inventory
    """

    inventoryType = models.ForeignKey(InventoryType, on_delete=models.CASCADE)
    building = models.ForeignKey(
        Building, on_delete=models.CASCADE, null=True, blank=True)
    work = models.ForeignKey(
        Work, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField()
    dateOrdered = models.DateField()
    dateReceived = models.DateField(null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)

    def cost(self):
        return self.quantity * self.inventoryType.rate

    def __str__(self):
        return self.inventoryType.name

    class Meta:
        abstract = True
        ordering = ['-id']


class InventoryConsumable(InventoryCommon):
    """
        Details about consumable inventory
        @fields-
            presentQuantity: presentQuantity of the item present in inventory
    """
    presentQuantity = models.IntegerField()


class InventoryNonConsumable(InventoryCommon):
    """
        Details about non-consumable inventory
        @fields-
            serial_no: serial no of inventory
            dateLastVerified: date when inventory was last verified
            issued_to: details about user which has consumed the inventory
    """
    serial_no = models.CharField(max_length=20)
    dateLastVerified = models.DateField()
    issued_to = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

FusionIIIT/templates/estate_module/Work/detail_modal.html
{% load humanize %}

<div class="ui modal details {{ menuitem|slugify }}_{{ work.id }}">
    <div class="header">
        {{ work.name }}
    </div>
    <div class="scrolling content">
        <div class="description">
            <div class="ui pointing secondary menu">
                <a class="item active" data-tab="{{ menuitem|slugify }}_{{ work.id }}_specifications"><i
                        class="bar chart icon"></i>Specifications</a>

                <a class="item" data-tab="{{ menuitem|slugify }}_{{ work.id }}_subworks"><i
                        class="sitemap icon"></i>SubWorks</a>
                {% if work.remarks %}
                <a class="item" data-tab="{{ menuitem|slugify }}_{{ work.id }}_remarks">
                    <i class="sticky note icon"></i>
                    Remarks
                </a>
                {% endif %}
            </div>

            {% comment %} <h4 class="ui horizontal divider header">
                <i class="bar chart icon"></i>
                Specifications

            </h4> {% endcomment %}

            <div class="ui tab basic segment active" data-tab="{{ menuitem|slugify }}_{{ work.id }}_specifications">
                <div class="ui two column centered grid">
                    <div class="ten wide column">
                        <table class="ui definition table">
                            <tbody>
                                <tr>
                                    <td class="six wide column">Name of work</td>
                                    <td class="name">{% if work.name %} {{ work.name }} {% endif %}</td>
                                </tr>

                                <tr>
                                    <td> Status </td>
                                    <td class=" 
                                {% if work.status == 'OS' %}
                                positive
                                {% elif work.status == 'DL' %}
                                warning
                                {% endif %}
                                ">
                                        {{ work.get_status_display }}
                                    </td>
                                </tr>

                                <tr>
                                    <td>Type of work</td>
                                    <td class="workType">{% if work.workType %} {{ work.get_workType_display }}
                                        {% endif %}
                                    </td>
                                </tr>

                                <tr>
                                    <td>Building</td>
                                    <td class="building">
                                        {% if work.building %}

                                        {{ work.building }}
                                        &nbsp;
                                        <button
                                            class="ui secondary mini button details building_{{ work.building.id }}">Details</button>
                                        {% else %}
                                        IIITDMJ
                                        {% endif %}
                                    </td>


                                </tr>

                                <tr>
                                    <td>Name of contractor</td>
                                    <td class="contractorName">{% if work.contractorName %} {{ work.contractorName }}
                                        {% endif %}
                                    </td>
                                </tr>

                                <tr>
                                    <td>Date Issued</td>
                                    <td class="dateIssued">{% if work.dateIssued %} {{ work.dateIssued }} {% endif %}
                                    </td>
                                </tr>

                                <tr>
                                    <td>Date Started</td>
                                    <td class="dateStarted">{% if work.dateStarted %} {{ work.dateStarted }} {% endif %}
                                    </td>
                                </tr>

                                <tr>
                                    <td>Date Completed</td>
                                    <td class="dateCompleted">{% if work.dateCompleted %} {{ work.dateCompleted }}
                                        {% endif %}</td>
                                </tr>

                                <tr>
                                    <td>Estimated cost</td>
                                    <td class="costEstimated">
                                        {% if work.costEstimated %}₹&nbsp;{{ work.costEstimated|intcomma }}
                                        {% endif %}
                                    </td>
                                </tr>

                                <tr>
                                    <td>Actual cost</td>
                                    <td class="costActual">{% if work.costActual %}₹&nbsp;{{ work.costActual|intcomma }}
                                        {% endif %}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        {% if work.verified is True %}
                        <div class="ui icon success compact message">
                            <i class="check icon"></i>
                            <div class="content">
                                <div class="header">
                                    This information has been verified
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="ui icon warning compact message">
                            <i class="exclamation triangle icon"></i>
                            <div class="content">
                                <div class="header">
                                    This information has not been verified
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="ui tab basic segment" data-tab="{{ menuitem|slugify }}_{{ work.id }}_subworks">
                {% if work.subwork_set.all|length > 0 %}
                <table class="ui selectable celled sortable table">
                    <thead>
                        <tr>
                            <th class="four wide column">Sub-Work Name</th>
                            <th class="right aligned">Date Issued</th>
                            <th class="right aligned">Date Started</th>
                            <th class="right aligned">Date Completed</th>
                            <th class="right aligned">Estimated cost</th>
                            <th colspan="2" class="two wide column"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for subWork in work.subwork_set.all %}
                        <tr>
                            <td class="four wide">
                                {{ subWork.name }}
                            </td>

                            <td class="right aligned dateIssued">{% if subWork.dateIssued %}
                                {{ subWork.dateIssued|date:'j-m-Y' }}
                                {% endif %}</td>

                            <td class="right aligned dateStarted">{% if subWork.dateStarted %}
                                {{ subWork.dateStarted|date:'j-m-Y' }}
                                {% endif %}
                            </td>

                            <td class="right aligned dateCompleted">{% if subWork.dateCompleted %}
                                {{ subWork.dateCompleted|date:'j-m-Y' }}
                                {% endif %}</td>

                            <td class="right aligned costEstimated">
                                {% if subWork.costEstimated %}₹&nbsp;{{ subWork.costEstimated|intcomma }}
                                {% endif %}
                            </td>
                            <td class="center aligned">
                                {% include subWork_data.template_dir|add:'/edit_button.html' %}
                            </td>
                            <td class="center aligned">
                                <button class="ui secondary button details subwork_{{ subWork.id }}">Details</button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th colspan="7">
                                <button
                                    class="ui right floated right labeled icon blue new_subwork_work_{{ work.id }} button">
                                    <i class="plus icon"></i>
                                    New
                                </button>
                            </th>
                        </tr>
                    </tfoot>
                </table>

                {% else %}
                <div class="ui two column centered grid">
                    <div class="row">
                        <div class="ui icon warning compact message">
                            <i class="database icon"></i>
                            <div class="content">
                                <div class="header">
                                    No Sub-Work found for {{ work.name }}
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <button class="ui right labeled icon blue new_subwork_work_{{ work.id }} button">
                            <i class="plus icon"></i>
                            New
                        </button>
                    </div>
                </div>
                {% endif %}
                <script type='module'>
                    $('.new_subwork_work_{{ work.id }}.button').on('click', function () {
                        $('.new_subwork.modal')
                            .modal({
                                centered: false
                            })
                            .modal({
                                onShow: function () {
                                    // prefill form
                                    $('.new_subwork.modal form')
                                        .form('set values', {
                                            work: '{{ work.id }}',
                                        });
                                }
                            })
                            .modal('setting', 'closable', false)
                            .modal('show');
                    });
                </script>
            </div>

            {% if work.remarks %}
            <div class="ui tab basic segment" data-tab="{{ menuitem|slugify }}_{{ work.id }}_remarks">
                <p>{{ work.remarks }}</p>
            </div>
            {% endif %}

        </div>
    </div>
    <div class="actions">
        <div class="ui black deny large button">
            Close
        </div>
    </div>
</div>
<script type='module'>
    $('.{{ menuitem|slugify }}_{{ work.id }}.details.modal')
        .modal({
            centered: false
        })
        .modal('setting', 'closable', false)
        .modal('attach events', '.{{ menuitem|slugify }}_{{ work.id }}.details.button',
            'show');
</script>

FusionIIIT/templates/estate_module/Work/edit.html
{% with 'edit_'|add:menuitem|add:'_form' as form_id %}
<div class="ui modal coupled_{{ menuitem|slugify }} edit_{{ menuitem|slugify }}">
    <div class="header">
        Edit {{ menuitem|slugify }}
    </div>
    <div class="scrolling content">
        <h4 class="ui horizontal divider header">
            <i class="info circle icon"></i>
            Main Information
        </h4>

        <form action="" id="{{ form_id }}" class="ui form" method="POST" novalidate>
            {% include 'estate_module/Work/form.html' %}
        </form>
    </div>
    <div class="actions">

        <button class="ui large red button delete_{{ menuitem|slugify }}">Delete</button>
        <button type="submit" form="{{ form_id }}" class="ui large right labeled icon green button">Update
            <i class="checkmark icon"></i></button>
        <div class="ui black deny large button">
            Cancel
        </div>
    </div>
</div>
{% endwith %}

<div class="ui tiny modal coupled_{{ menuitem|slugify }} delete_{{ menuitem|slugify }}">
    <div class="header">
        Delete
    </div>

    <div class="content">
        <p></p>
        <form id="delete_{{ menuitem|slugify }}_form" action="" method="POST">
            {% csrf_token %}
        </form>
    </div>
    <div class="actions">

        <div class="ui submit green deny large button">No</div>

        <button type="submit" form="delete_{{ menuitem|slugify }}_form"
            class="ui negative right labeled icon large button">Yes<i class="checkmark icon"></i></button>
    </div>
</div>

FusionIIIT/templates/estate_module/Work/edit_button.html
<button class="ui red button edit_{{ menuitem|slugify }}_{{ work.id }}">Edit</button>
<script type='module'>
    $('.coupled_{{ menuitem|slugify }}.modal')
        .modal({
            allowMultiple: true
        });

    $('.delete_{{ menuitem|slugify }}.modal')
        .modal('attach events',
            '.edit_{{ menuitem|slugify }}.modal .delete_{{ menuitem|slugify }}.button');

    $('.edit_{{ menuitem|slugify }}_{{ work.id }}.button').on('click', function () {
        $('.edit_{{ menuitem|slugify }}.modal')
            .modal({
                centered: false
            })
            .modal({
                onShow: function () {
                    // change edit modal header
                    $('.edit_{{ menuitem|slugify }}.modal .header').first()
                        .text("{{ work.name }}");
                    // change modal form action url
                    $('.edit_{{ menuitem|slugify }}.modal form')
                        .attr("action", "{% url 'edit_work' work.id %}");
                    // change delete modal message
                    $('.delete_{{ menuitem|slugify }}.modal .content p')
                        .text("Are you sure you want to delete {{ work.name }}?");
                    // change delete form action url
                    $('.delete_{{ menuitem|slugify }}.modal form')
                        .attr("action", "{% url 'delete_work' work.id %}");
                    // prefill form
                    $('.edit_{{ menuitem|slugify }}.modal form')
                        .form('set values', {
                            name: '{% if work.name %}{{ work.name }}{% endif %}',
                            workType: '{% if work.workType %}{{ work.workType }}{% endif %}',
                            building: '{% if work.building %}{{ work.building.id }}{% endif %}',
                            contractorName: '{% if work.contractorName %}{{ work.contractorName }}{% endif %}',
                            dateIssued: '{% if work.dateIssued %}{{ work.dateIssued }}{% endif %}',
                            dateStarted: '{% if work.dateStarted %}{{ work.dateStarted }}{% endif %}',
                            dateCompleted: '{% if work.dateCompleted %}{{ work.dateCompleted }}{% endif %}',
                            costEstimated: '{% if work.costEstimated %}{{ work.costEstimated }}{% endif %}',
                            costActual: '{% if work.costActual %}{{ work.costActual }}{% endif %}',
                            status: '{{ work.status }}',
                            verified: '{{ work.verified }}',
                            remarks: '{% if work.remarks %}{{ work.remarks }}{% endif %}',
                        });
                    /*$('.edit_{{ menuitem|slugify }}.modal #id_name')
                        .val("{{ work.name }}");
                    $('.edit_{{ menuitem|slugify }}.modal #id_workType')
                        .val("{{ work.workType }}");
                    $(".edit_{{ menuitem|slugify }}.modal #id_estate option[value='{{ work.estate.id }}']")
                        .attr(
                            'selected', 'selected');
                    $('.edit_{{ menuitem|slugify }}.modal #id_contractorName')
                        .val("{{ work.contractorName }}");
                    $('.edit_{{ menuitem|slugify }}.modal #id_dateIssued')
                        .val("{{ work.dateIssued|date:'Y-m-d' }}");
                    $('.edit_{{ menuitem|slugify }}.modal #id_dateStarted')
                        .val("{{ work.dateStarted|date:'Y-m-d' }}");
                    $('.edit_{{ menuitem|slugify }}.modal #id_dateCompleted')
                        .val("{{ work.dateCompleted|date:'Y-m-d' }}");
                    $('.edit_{{ menuitem|slugify }}.modal #id_costEstimated')
                        .val("{{ work.costEstimated }}");
                    $('.edit_{{ menuitem|slugify }}.modal #id_costActual')
                        .val("{{ work.costActual }}");
                    $('.edit_{{ menuitem|slugify }}.modal #id_remarks')
                        .val("{{ work.remarks }}");*/
                }
            })
            .modal('setting', 'closable', false)
            .modal('show');
    });
</script>