FusionIIIT/Fusion/urls.py
import notifications.urls
import debug_toolbar
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls')),
    url(r'^aims/', include('applications.academic_information.urls')),
    url(r'^notifications/', include('applications.notifications_extension.urls')),
    url(r'^estate/', include('applications.estate_module.urls')),
    url(r'^dep/', include('applications.department.urls')),
    url(r'^programme_curriculum/',include('applications.programme_curriculum.urls')),
    url(r'^iwdModuleV2/', include('applications.iwdModuleV2.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^research_procedures/', include('applications.research_procedures.urls')),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^eis/', include('applications.eis.urls')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^purchase-and-store/', include('applications.ps1.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^establishment/', include('applications.establishment.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^counselling/', include('applications.counselling_cell.urls')),
    url(r'^hostelmanagement/', include('applications.hostel_management.urls')),
    url(r'^income-expenditure/', include('applications.income_expenditure.urls')),
    url(r'^hr2/', include('applications.hr2.urls')),
    url(r'^recruitment/', include('applications.recruitment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FusionIIIT/applications/filetracking/urls.py
from django.conf.urls import url

from . import views

app_name = 'filetracking'

urlpatterns = [

    url(r'^$', views.filetracking, name='filetracking'),
    url(r'^drafts/$', views.drafts, name='drafts'),
    url(r'^fileview/(?P<id>\d+)$', views.fileview, name='fileview'),
    url(r'^fileview1/(?P<id>\d+)$', views.fileview1, name='fileview1'),
    url(r'^fileview2/(?P<id>\d+)$', views.fileview2, name='fileview2'),
    url(r'^outward/$', views.outward, name='outward'),
    url(r'^inward/$', views.inward, name='inward'),
    url(r'^confirmdelete/(?P<id>\d+)$', views.confirmdelete, name='confirm_delete'),
    url(r'^archive/(?P<id>\d+)/$', views.archive, name='archive'),
    url(r'^finish/(?P<id>\d+)/$', views.finish, name='finish'),
    url(r'^forward/(?P<id>\d+)/$', views.forward, name='forward'),
    url(r'^ajax/$', views.AjaxDropdown1, name='ajax_dropdown1'),
    url(r'^ajax_dropdown/$', views.AjaxDropdown, name='ajax_dropdown'),
    url(r'^test/$',views.test, name='test'),
    url(r'^delete/(?P<id>\d+)$',views.delete, name='delete'),
    url(r'^forward_inward/(?P<id>\d+)/$', views.forward_inward, name='forward_inward'),

    ## correction team 24
    url(r'^finish_design/$', views.finish_design, name='finish_design'),
    url(r'^finish_fileview/(?P<id>\d+)$', views.finish_fileview, name='finish_fileview'),
    url(r'^archive_design/$', views.archive_design, name='archive_design'),
    url(r'^archive_finish/(?P<id>\d+)/$', views.archive_finish, name='archive_finish'),
]

FusionIIIT/applications/filetracking/models.py
from django.db import models
from django.contrib.auth.models import User
from applications.globals.models import ExtraInfo, HoldsDesignation, Designation


class File(models.Model):
    """
    This is file table which contains the all the files created by user
    """
    uploader = models.ForeignKey(ExtraInfo, on_delete=models.CASCADE, related_name='uploaded_files')
    designation = models.ForeignKey(Designation, on_delete=models.CASCADE, null=True, related_name='upload_designation')
    subject = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=400, null=True, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    upload_file = models.FileField(blank=True)
    is_read = models.BooleanField(default = False)


    class Meta:
        db_table = 'File'

    #def __str__(self):
        #return str(self.ref_id)


class Tracking(models.Model):
    """
    This is File Tracing Table which contains the status of each indivisual file created by the user 
    """
    file_id = models.ForeignKey(File, on_delete=models.CASCADE, null=True)
    current_id = models.ForeignKey(ExtraInfo, on_delete=models.CASCADE)
    current_design = models.ForeignKey(HoldsDesignation, null=True, on_delete=models.CASCADE)
        # receiver_id = models.ForeignKey(ExtraInfo, on_delete=models.CASCADE, related_name='receiver_id')
    # receive_design = models.ForeignKey(HoldsDesignation, null=True, on_delete=models.CASCADE, related_name='rec_design')
    receiver_id = models.ForeignKey(User,null = True, on_delete=models.CASCADE, related_name='receiver_id')
    receive_design = models.ForeignKey(Designation, null=True, on_delete=models.CASCADE, related_name='rec_design')

    receive_date = models.DateTimeField(auto_now_add=True)
    forward_date = models.DateTimeField(auto_now_add=True)
    remarks = models.CharField(max_length=250, null=True, blank=True)
    upload_file = models.FileField(blank=True)
    is_read = models.BooleanField(default = False)

    class Meta:
        db_table = 'Tracking'

FusionIIIT/applications/filetracking/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import File, Tracking
from applications.globals.models import ExtraInfo, HoldsDesignation, Designation
from django.template.defaulttags import csrf_token
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.core import serializers
from django.contrib.auth.models import User
from timeit import default_timer as time
from notification.views import office_module_notif,file_tracking_notif
from .utils import *


@login_required(login_url = "/accounts/login/")
def filetracking(request):
    """
        The function is used to create files by current user(employee).
        It adds the employee(uploader) and file datails to a file(table) of filetracking(model)
        if he intends to create file.

        @param:
                request - trivial.

        @variables:


                uploader - Employee who creates file.
                subject - Title of the file.
                description - Description of the file.
                upload_file - Attachment uploaded while creating file.
                file - The file object.
                extrainfo - The Extrainfo object.
                holdsdesignations - The HoldsDesignation object.
                context - Holds data needed to make necessary changes in the template.
    """
    if request.method =="POST":
        try:
            if 'save' in request.POST:
                uploader = request.user.extrainfo
                subject = request.POST.get('title')
                description = request.POST.get('desc')
                design = request.POST.get('design')
                designation = Designation.objects.get(id = HoldsDesignation.objects.select_related('user','working','designation').get(id = design).designation_id)
                upload_file = request.FILES.get('myfile')
                if(upload_file.size / 1000 > 10240):
                    messages.error(request,"File should not be greater than 10MB")
                    return redirect("/filetracking")               

                File.objects.create(
                    uploader=uploader,
                    description=description,
                    subject=subject,
                    designation=designation,
                    upload_file=upload_file
                )

                messages.success(request,'File Draft Saved Successfully')

            if 'send' in request.POST:
                uploader = request.user.extrainfo
                subject = request.POST.get('title')
                description = request.POST.get('desc')
                design = request.POST.get('design')
                designation = Designation.objects.get(id = HoldsDesignation.objects.select_related('user','working','designation').get(id = design).designation_id)

                upload_file = request.FILES.get('myfile')
                if(upload_file.size / 1000 > 10240):
                    messages.error(request,"File should not be greater than 10MB")
                    return redirect("/filetracking")

                file = File.objects.create(
                    uploader=uploader,
                    description=description,
                    subject=subject,
                    designation=designation,
                    upload_file=upload_file
                )


                current_id = request.user.extrainfo
                remarks = request.POST.get('remarks')

                sender = request.POST.get('design')
                current_design = HoldsDesignation.objects.select_related('user','working','designation').get(id=sender)

                receiver = request.POST.get('receiver')
                try:
                    receiver_id = User.objects.get(username=receiver)
                except Exception as e:
                    messages.error(request, 'Enter a valid Username')
                    return redirect('/filetracking/')
                receive = request.POST.get('recieve')
                try:
                    receive_design = Designation.objects.get(name=receive)
                except Exception as e:
                    messages.error(request, 'Enter a valid Designation')
                    return redirect('/filetracking/')

                upload_file = request.FILES.get('myfile')

                Tracking.objects.create(
                    file_id=file,
                    current_id=current_id,
                    current_design=current_design,
                    receive_design=receive_design,
                    receiver_id=receiver_id,
                    remarks=remarks,
                    upload_file=upload_file,
                )
                #office_module_notif(request.user, receiver_id)
                file_tracking_notif(request.user,receiver_id,subject)
                messages.success(request,'File sent successfully')

        except IntegrityError:
            message = "FileID Already Taken.!!"
            return HttpResponse(message)



    file = File.objects.select_related('uploader__user','uploader__department','designation').all()
    extrainfo = ExtraInfo.objects.select_related('user','department').all()
    holdsdesignations = HoldsDesignation.objects.select_related('user','working','designation').all()
    designations = get_designation(request.user)

    context = {
        'file': file,
        'extrainfo': extrainfo,
        'holdsdesignations': holdsdesignations,
        'designations': designations,
    }
    return render(request, 'filetracking/composefile.html', context)


@login_required(login_url = "/accounts/login")
def drafts(request):
    """
        The function is used to get the designation of the user and renders it on draft template.

        @param:
                request - trivial.

        @variables:
                
                
                context - Holds data needed to make necessary changes in the template.
    """
    designation = get_designation(request.user)
    context = {
        'designation': designation,
    }
    return render(request, 'filetracking/drafts.html', context)


@login_required(login_url = "/accounts/login")
def fileview(request,id):

    """
    This function is used to veiw all all created files by the user ordered by upload date.it collects all the created files from File object.

    @param:
      request - trivial
      id - user id 

    @parameters
      draft - file obeject containing all the files created by user
      context - holds data needed to render the template
      

    
    """
    # draft = File.objects.select_related('uploader__user','uploader__department','designation').filter(uploader=request.user.extrainfo).order_by('-upload_date')
    # extrainfo = ExtraInfo.objects.select_related('user','department').all()

    extrainfo = ExtraInfo.objects.select_related('user','department').all()
  
    ids = File.objects.filter(uploader=request.user.extrainfo).order_by('-upload_date').values_list('id', flat=True)
    draft_files_pk=[]
    
    for i in ids: 
       file_tracking_ids = Tracking.objects.filter(file_id=i).values_list('id', flat=True)
       if(len(file_tracking_ids)==0):
        draft_files_pk.append(i)
    
    draft_file_list=[]
    for i in draft_files_pk:
        draft_file_list.append(File.objects.get(pk=i))



    user_designation = HoldsDesignation.objects.select_related('user','working','designation').get(pk=id)
    s = str(user_designation).split(" - ")
    designations = s[1]
    context = {

        'draft': draft_file_list,
        'extrainfo': extrainfo,
        'designations': designations,
    }
    return render(request, 'filetracking/fileview.html', context)



@login_required(login_url = "/accounts/login")
def fileview1(request,id):

    """
         The function is used to get all the files sent by user(employee) to other employees
        which are filtered from Tracking(table) objects by current user i.e. current_id.
        It displays files sent by user to other employees of a Tracking(table) of filetracking(model)
        in the 'Outbox' tab of template.

        @param:
                request - trivial.
                id - user id 

        @variables:
                out - The Tracking object filtered by current_id i.e, present working user.
                context - Holds data needed to make necessary changes in the template.
    
    """

    outward_files = Tracking.objects.select_related('file_id__uploader__user','file_id__uploader__department','file_id__designation','current_id__user','current_id__department',
    'current_design__user','current_design__working','current_design__designation','receiver_id','receive_design').filter(current_id=request.user.extrainfo).order_by('-forward_date')

    user_designation = HoldsDesignation.objects.select_related('user','working','designation').get(pk=id)

    context = {

        'out': outward_files,
        'abcd': user_designation,
    }
    return render(request, 'filetracking/fileview1.html', context)


@login_required(login_url = "/accounts/login")
def fileview2(request,id):

    """
    The function is used to fetch the files received by the user form other employees. 
    These files are filtered by receiver id and ordered by receive date.

         @param:
                request - trivial.
                id - user id

        @variables: 
                inward_file - The Tracking object filtered by receiver_id i.e, present working user.
                context - Holds data needed to make necessary changes in the template. 

    """
    inward_file = Tracking.objects.select_related('file_id__uploader__user','file_id__uploader__department','file_id__designation','current_id__user','current_id__department',

FusionIIIT/templates/filetracking/archive.html
{% extends 'filetracking/filetracking.html' %}
{% load static %}

{% block filetracking_tab %}
    <div class="ui pointing secondary menu">
        <h3>
            <a class="active item" data-tab="inward">
            Archived Files 
            </a>
        </h3>

    </div>

    <div class="ui divider"></div>

    <table class="ui very basic celled sortable table">
        <thead>
        <tr>
            <th>Created By</th>
            <th>File ID</th>
            <th>Subject</th>
            <th>Date</th>
            <th>View File</th>
            <th>Forward</th>
          
        </tr>
        </thead>
        <tbody>
        {% for j in draft %}
          {% ifequal designations j.designation|stringformat:'s' %}
             <tr>
                 <td>{{j.uploader.user}} - {{j.designation}}</td>
                 <td>{{request.user.extrainfo.department.name}}-{{j.upload_date.year}}-{{j.upload_date.month}}-#{{j.id}}</td>
                 <td>{{j.subject}}</td>
                 <td>{{j.upload_date}}</td>
                 <td><a href="{% url 'filetracking:archive_finish' j.id %}"><button class="ui primary button">
                              View
                    </button></a></td>
                    <td><a href="{% url 'filetracking:forward' j.id %}"><button class="ui primary button">
                        Forward
              </button></a></td>

                
              </tr>
          {% endifequal %}
        {% endfor %}
        </tbody>

    </table>

    <br>

{% endblock %}

FusionIIIT/templates/filetracking/confirmdelete.html
{% extends 'filetracking/filetracking.html' %}
{% load static %}

{% block filetracking_tab %}
<html>
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Float cancel and delete buttons and add an equal width */
.cancelbtn, .deletebtn {
  float: left;
  width: 50%;
}

/* Add a color to the cancel button */
.cancelbtn {
  background-color: #ccc;
  color: black;
}

/* Add a color to the delete button */
.deletebtn {
  background-color: #f44336;
}

/* Add padding and center-align text to the container */
.container {
  padding: 16px;
  text-align: center;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: #474e5d;
  padding-top: 50px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* Style the horizontal ruler */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* The Modal Close Button (x) */
.close {
  position: absolute;
  right: 35px;
  top: 15px;
  font-size: 40px;
  font-weight: bold;
  color: #f1f1f1;
}

.close:hover,
.close:focus {
  color: #f44336;
  cursor: pointer;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and delete button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .deletebtn {
     width: 100%;
  }
}
</style>
<div class="container">
      <h1>Delete file</h1>
      <p>Are you sure you want to delete?</p>

      <div class="clearfix">

         <a type="button" href="/filetracking/drafts/"> <button >Cancel</button></a>

        <a href="{% url 'filetracking:delete' j.id %}"><button >Delete</button></a>
      </div>
    </div>



</body>
</html>
{% endblock %}

FusionIIIT/templates/filetracking/drafts.html
{% extends 'filetracking/filetracking.html' %}
{% load static %}

{% block filetracking_tab %}
    <div class="ui pointing secondary menu">
        <h3>
            <a class="active item" data-tab="inward">
            Drafts
            </a>
        </h3>

    </div>
<table class="ui very basic celled sortable table">
<div class="field">
                    <label>Select designation:
<!--                        <select required class="ui fluid search selection dropdown" name="designation">-->
<!--                           <option selected hidden>Select</option>-->
<!--                         <form action="/filetracking/fileview/" method="get">-->
                             {% for designation in designation %}
                             <td> <a href="{% url 'filetracking:fileview' designation.id %}"><button class="ui primary button">
                                 {{designation}}
                             </button></a></td>
                            {% endfor %}
<!--                         </form>-->
                        </select>
                    </label>
                </div>
</table>

{% endblock %}

FusionIIIT/templates/filetracking/fileview1.html
{% extends 'filetracking/filetracking.html' %}
{% load static %}

{% block filetracking_tab %}
    <div class="ui pointing secondary menu">
        <h3>
            <a class="active item" data-tab="outward">
            Outward Files
            </a>
        </h3>
    </div>

    <div class="ui divider"></div>

    <table class="ui sortable very basic celled table">
        <thead>
        <tr>
            <th>Sent As</th>
            <th>Sent To</th>
            <th>File ID</th>
            <th>Subject</th>
            <th>Date</th>
            <th>View File</th>
        </tr>
        </thead>
        <tbody>

    {% for i in out %}
     {% ifequal abcd i.current_design %}
       <tr>
           <td>{{i.current_design}}</td>
           <td>{{i.receiver_id}}-{{i.receive_design}}</td>
           <td>{{i.file_id.uploader.department.name}}-{{i.file_id.upload_date.year}}-{{i.file_id.upload_date.month}}-#{{i.file_id.id}}</td>
           <td>{{i.file_id.subject}}</td>
           <td>{{i.receive_date}}</td>
           <td><a href="{% url 'filetracking:forward' i.file_id.id %}"><button class="ui primary button">
                  View
             </button></a>
           </td>

       </tr>
     {% endifequal %}
    {% endfor %}
        </tbody>

    </table>
    <br>

{% endblock %}

FusionIIIT/templates/filetracking/fileview2.html
{% extends 'filetracking/filetracking.html' %}
{% load static %}

{% block filetracking_tab %}
    <div class="ui pointing secondary menu">
        <h3>
            <a class="active item" data-tab="inward">
            Inward Files
            </a>
        </h3>

    </div>

    <div class="ui divider"></div>

    <table class="ui very basic celled sortable table">
        <thead>
        <tr>
            <th>Received as</th>
            <th>Send by</th>
            <th>File ID</th>
            <th>Subject</th>
            <th>Date</th>
            <th>View File</th>
<!--            <th>R/UnR</th>-->
        </tr>
        </thead>

        <tbody>
        {% for j in in_file %}
            {% ifequal designations j.receive_design|stringformat:'s' %}
            <tr>
                <td>{{request.user.extrainfo.user}} - {{j.receive_design}}</td>
                <td>{{j.current_design}}</td>
                <td>{{j.file_id.uploader.department.name}}-{{j.file_id.upload_date.year}}-{{j.file_id.upload_date.month}}-#{{j.file_id.id}}  </td>
                <td>{{j.file_id.subject}}</td>
                <td>{{j.receive_date}}</td>
                <td><a href="{% url 'filetracking:forward' j.file_id.id %}"><button class="ui primary button">
                              View
                    </button></a></td>







              </tr>
            {% endifequal %}
        {% endfor %}
        </tbody>

    </table>

    <br>

{% endblock %}

FusionIIIT/templates/filetracking/finish_design.html
{% extends 'filetracking/filetracking.html' %}
{% load static %}

{% block filetracking_tab %}
    <div class="ui pointing secondary menu">
        <h3>
            <a class="active item" data-tab="inward">
            Choose Designation to Track Files
            </a>
        </h3>

    </div>

    <div class="ui divider"></div>

    <table class="ui very basic celled sortable table">
        <div class="field">
                    <label>Select designation:
<!--                        <select required class="ui fluid search selection dropdown" name="designation">-->
<!--                           <option selected hidden>Select</option>-->
<!--                         <form action="/filetracking/fileview/" method="get">-->
                             {% for designation in designation %}
                             <td> <a href="{% url 'filetracking:finish_fileview' designation.id %}"><button class="ui primary button">
                                 {{designation}}
                             </button></a></td>
                            {% endfor %}
<!--                         </form>-->
                        </select>
                    </label>
                </div>

    </table>

    <br>

{% endblock %}

FusionIIIT/templates/filetracking/finish_fileview.html
{% extends 'filetracking/filetracking.html' %}
{% load static %}

{% block filetracking_tab %}
    <div class="ui pointing secondary menu">
        <h3>
            <a class="active item" data-tab="outward">
            Files to Track
            </a>
        </h3>
    </div>

    <div class="ui divider"></div>

    <table class="ui sortable very basic celled table">
        <thead>
        <tr>
            <th>Sent As</th>
            <th>Sent To</th>
            <th>File ID</th>
            <th>Subject</th>
            <th>Date</th>
            <th>View File</th>
            <th>Finish File</th>
            
        </tr>
        </thead>
        <tbody>

    {% for i in out %}
     {% ifequal abcd i.current_design %}
       <tr>
           <td>{{i.current_design}}</td>
           <td>{{i.receiver_id}}-{{i.receive_design}}</td>
           <td>{{i.file_id.uploader.department.name}}-{{i.file_id.upload_date.year}}-{{i.file_id.upload_date.month}}-#{{i.file_id.id}}</td>
           <td>{{i.file_id.subject}}</td>
           <td>{{i.receive_date}}</td>
           <td><a href="{% url 'filetracking:forward' i.file_id.id %}"><button class="ui primary button">
                  View
             </button></a>
           </td>
           <td><a href="{% url 'filetracking:finish' i.file_id.id %}"><button class="ui primary button">
            Finish
       </button></a>
     </td>

       </tr>
     {% endifequal %}
    {% endfor %}
        </tbody>

    </table>
    <br>

{% endblock %}

FusionIIIT/templates/filetracking/inward.html
{% extends 'filetracking/filetracking.html' %}
{% load static %}

{% block filetracking_tab %}
    <div class="ui pointing secondary menu">
        <h3>
            <a class="active item" data-tab="inward">
            Inward Files
            </a>
        </h3>

    </div>

    <div class="ui divider"></div>

    <table class="ui very basic celled sortable table">
        <div class="field">
                    <label>Select designation:
<!--                        <select required class="ui fluid search selection dropdown" name="designation">-->
<!--                           <option selected hidden>Select</option>-->
<!--                         <form action="/filetracking/fileview/" method="get">-->
                             {% for designation in designation %}
                             <td> <a href="{% url 'filetracking:fileview2' designation.id %}"><button class="ui primary button">
                                 {{designation}}
                             </button></a></td>
                            {% endfor %}
<!--                         </form>-->
                        </select>
                    </label>
                </div>

    </table>

    <br>

{% endblock %}

FusionIIIT/templates/filetracking/track.html
{% extends 'filetracking/filetracking.html' %}
{% load static %}

{% block filetracking_tab %}
    <div class="ui pointing secondary menu">
        <h3>
            <a class="active item" data-tab="track">
            Track File
            </a>
        </h3>
    </div>

    {% comment %}The Technology segment starts here!{% endcomment %}

    <div class="ui vertical stripe team segment" style="padding-left: 3.5%;
                padding-right: 3.5%;">

        <form class="ui large form">
            <div class="one field">

                <label>File Ref No.</label>
                <div class="ui action small input eleven wide field">
                    <input type="number" placeholder="Search..." name="fileid">
                    <a href="/filetracking/trackfile"><button class="ui teal button" name="track">Track</button></a>
                </div>
            </div>
        </form>

        <br>
        <br>

    </div>
    {% comment %}The Technology segment ends here!{% endcomment %}

    <br>

{% endblock %}